((label . "String Utils")
 (functions (item-callback "Abstract variable"))
 (shortcut . #f)
 (shortcut-prefix . #f)
 (help-string . "Help String")
 (output-to . selection)
 (persistent . #f)
 (active . #t))
