((label . "Snippets")
 (functions . ((author-date "author date")
               (author-date-time "author date time")
               (author-email-date "author email date")
               (author-email-date-time "author email date time")
               (license-wtfpl "License WTFPL")
               (license-mit "License MIT")))
 (shortcut . #f)
 (shortcut-prefix . #f)
 (help-string . "Help String")
 (output-to . selection)
 (active . #t))
