((label . "String Utils")
 (functions . ((item-callback "Word completion")))
 (shortcut . #\/)
 (shortcut-prefix . (ctl shift))
 (help-string . "Help String")
 (output-to . selection)
 (active . #t))
