((label . "Enter submodule")
 (functions . ((enter-drracket "drracket")
               (enter-main "main")
               (enter-test "test")))
 (shortcut . #f)
 (shortcut-prefix . #f)
 (help-string . "Help String")
 (output-to . selection)
 (persistent . #f)
 (active . #t))
