((label . "Enter submodule")
 (functions . ((enter-drracket "drracket")))
 (shortcut . f5)
 (shortcut-prefix . (shift))
 (help-string . "Help String")
 (output-to . selection)
 (persistent . #f)
 (active . #t))

((label . "Enter submodule")
 (functions . ((enter-main "main")
               (enter-test "test")))
 (help-string . "Help String")
 (output-to . selection)
 (persistent . #f)
 (active . #t))
