((label . "Git")
 (functions (git-commit-file "Commit file")
            (git-commit-all "Commit all")
            (git-push "Push")
            (git-pull-rebase "Pull --rebase")
            (git-add-file "Add file")
            )
 (shortcut . #f)
 (shortcut-prefix . #f)
 (help-string . "Help String")
 (output-to . selection)
 (persistent . #f)
 (active . #t))
