((label . "GUI Tools")
 (functions . ((add-frame "Add frame")
               (add-message "Add message")))
 (shortcut . #f)
 (shortcut-prefix . #f)
 (help-string . "Help String")
 (output-to . selection)
 (persistent . #f)
 (active . #t))
