((label . "String Utils")
 (functions . ((item-callback "Table Indent (double-space)")))
 (shortcut . #\I)
 (shortcut-prefix . (ctl shift))
 (help-string . "Help String")
 (output-to . selection)
 (active . #t))
