((label . "Utils")
 (functions (item-callback "Open racket/collects file"))
 (shortcut . #f)
 (shortcut-prefix . #f)
 (help-string . "Help String")
 (output-to . selection)
 (persistent . #f)
 (active . #t))
